"""
Quantitative Comparison: Our LoReFTExtractor vs PyReFT
======================================================

Trains BOTH methods on the *same* refusal_cast_responses data, then compares
learned subspaces using:

  1. Principal angles between rotation subspaces (cos of canonical angles)
  2. Frobenius distance of projectors: ||R_ours R_ours^T - R_gt R_gt^T||_F
  3. Cosine similarity of learned source transforms (W matrices)
  4. Orthonormality sanity check: ||R R^T - I||_F ≈ 0

NO mock functions. Both methods are trained from random init on real data.

Usage (from repo root, sae_circuit env):
    conda run -n sae_circuit python Scripts/compare_loreft_vs_axbench.py \\
        [--layer 10] [--n-samples 100] [--epochs 3] [--rank 4] \\
        [--device cuda:0] [--seed 42] [--skip-our-run]
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

# ---------------------------------------------------------------------------
# Repo root on sys.path
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "Code" / "pyreft"))


# ===========================================================================
# Subspace comparison utilities
# ===========================================================================

def principal_angles(R1: torch.Tensor, R2: torch.Tensor) -> torch.Tensor:
    """
    Principal angles between the row-spaces of R1 (r×d) and R2 (r×d).
    Both must have orthonormal rows (||r_i||=1, r_i·r_j=0).
    """
    M = R1.float() @ R2.float().T  # (r, r)
    sv = torch.linalg.svdvals(M).clamp(-1.0, 1.0)
    return sv.acos().sort().values


def projector_frobenius(R1: torch.Tensor, R2: torch.Tensor) -> tuple[float, float]:
    """
    ||P1 - P2||_F where Pi = R_i^T R_i (orthogonal projector onto rowspace).
    Returns (raw, normalised_by_sqrt_2r).
    """
    P1 = R1.float().T @ R1.float()  # (d, d)
    P2 = R2.float().T @ R2.float()
    raw = (P1 - P2).norm(p="fro").item()
    return raw, raw / (2 * R1.shape[0]) ** 0.5


def cos_sim_flat(A: torch.Tensor, B: torch.Tensor) -> float:
    a, b = A.float().flatten(), B.float().flatten()
    return F.cosine_similarity(a.unsqueeze(0), b.unsqueeze(0)).item()


def orthonormality_err(R: torch.Tensor) -> float:
    gram = R.float() @ R.float().T
    I = torch.eye(gram.shape[0])
    return (gram - I).norm(p="fro").item()


def subspace_principal_angles(W1: torch.Tensor, W2: torch.Tensor) -> torch.Tensor:
    """Principal angles between row-spaces of W1, W2 (after QR-orthogonalising)."""
    Q1, _ = torch.linalg.qr(W1.float().T)  # (d, r)
    Q2, _ = torch.linalg.qr(W2.float().T)
    return principal_angles(Q1.T, Q2.T)


# ===========================================================================
# Step A — Our LoReFT pipeline
# ===========================================================================

def run_our_pipeline(
    layer: int,
    n_samples: int,
    epochs: int,
    lr: float,
    rank: int,
    device: str,
    seed: int,
    dataset: str = "refusal_cast_responses",
) -> Path:
    """
    Write a temporary config JSON and run python -m Steering.cli.
    """
    vector_dir = str(REPO_ROOT / "Vector" / "LOREFT" / "concept500_compare")

    cfg = {
        "name": "loreft_concept500_compare",
        "description": "LoReFT comparison run (auto-generated by compare script).",
        "model": {
            "name": "google/gemma-2-2b-it",
            "device": device,
            "dtype": "bfloat16",
            "max_new_tokens": 64,
            "do_sample": False,
        },
        "extractor": {
            "method": "LOREFT",
            "layer": [layer],
            "batch_size": 4,
            "position": "last",
            "apply_chat_template": True,
            "hook_point": "pre",
            "change_pad_token": False,
            "reft_type": "Loreft",
            "low_rank_dimension": rank,
            "dropout": 0.0,
            "act_fn": "linear",
            "add_bias": True,
            "lr": lr,
            "weight_decay": 0.0,
            "epochs": epochs,
        },
        "steer": {
            "method": "LOREFT",
            "layer": [layer],
            "coeff": 1,
            "apply_chat_template": True,
            "hook_point": "pre",
            "position": "last",
            "batch_size": 4,
            "norm": False,
            "apply_all_layers": False,
            "reft_type": "Loreft",
            "low_rank_dimension": rank,
            "dropout": 0.0,
            "act_fn": "linear",
            "add_bias": True,
        },
        "post_process": {},
        "train_dataset": dataset,
        "n_train": n_samples,
        "test_dataset": "refusal_open",
        "n_test": 10,
        "output": "Results/LOREFT_compare",
        "save_samples": False,
        "include_baseline": False,
        "compute_perplexity": False,
        "seed": seed,
        "save_vector": vector_dir,
    }

    tmp_cfg = REPO_ROOT / "Configs" / "Eval" / "REFT" / "_loreft_compare_tmp.json"
    with open(tmp_cfg, "w") as f:
        json.dump(cfg, f, indent=2)

    print(f"\n[Step A] Running our LoReFT pipeline — layer={layer}, n={n_samples}, epochs={epochs}")
    cmd = [
        "conda", "run", "-n", "sae_circuit",
        "python", "-m", "Steering.cli",
        "--config", str(tmp_cfg),
    ]
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        raise RuntimeError(f"LoReFT pipeline failed (exit {result.returncode})")

    print("[Step A] Done.")
    return Path(vector_dir)


# ===========================================================================
# Step B — PyReFT ground truth
# ===========================================================================

def _load_cast_refusal_data(n_samples: int | None, tokenizer, dataset: str = "refusal_cast_responses"):
    """
    Use our DataLoader to get the dataset.
    Returns raw data.
    """
    from Steering.data import DataLoader as SDLoader

    loader = SDLoader()
    data = loader.load(
        dataset,
        n_samples=n_samples,
        apply_chat_template=False,  # keep raw question and response suffixes
        tokenizer=tokenizer,
    )
    return data


def _build_axbench_prompt(tokenizer, question: str) -> str:
    messages = [{"role": "user", "content": question}]
    prompt_ids = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    return prompt_ids


def train_pyreft_gt(
    data: list,
    tokenizer,
    layer: int,
    rank: int,
    epochs: int,
    lr: float,
    batch_size: int,
    device: str,
    seed: int,
) -> dict:
    """
    Train official PyReFT on the refusal data.
    """
    import pyreft
    from transformers import AutoModelForCausalLM, get_scheduler
    from torch.utils.data import DataLoader as TorchDataLoader
    import pandas as pd

    print(f"\n[Step B] Training PyReFT GT "
          f"(layer={layer}, r={rank}, epochs={epochs}, lr={lr})")

    torch.manual_seed(seed)

    # Load model
    print("  Loading google/gemma-2-2b-it ...")
    model = AutoModelForCausalLM.from_pretrained(
        "google/gemma-2-2b-it",
        torch_dtype=torch.bfloat16,
    ).to(device)
    model.eval()
    d_model = model.config.hidden_size

    # Build intervention config
    # In HookedTransformer it is pre-hook, in pyvene it is "block_output"
    reft_config = pyreft.ReftConfig(representations=[{
        "layer": layer,
        "component": "block_output",
        "low_rank_dimension": rank,
        "intervention": pyreft.LoreftIntervention(
            embed_dim=d_model,
            low_rank_dimension=rank,
        )
    }])
    ax_model = pyreft.get_reft_model(model, reft_config)
    ax_model.set_device(device)
    ax_model.train()

    # Build inputs/outputs list
    inputs_list = []
    outputs_list = []
    for d in data:
        q = d.get("question", "")
        win_out = d.get("correct_prompt", "")  # refusing suffix
        if not q or not win_out:
            continue
        prompt = _build_axbench_prompt(tokenizer, q)
        inputs_list.append(prompt)
        outputs_list.append(win_out)

    print(f"  Dataset size: {len(inputs_list)} samples")

    # Make supervised data module: positions="f1+l1" matches standard pyreft defaults
    data_module = pyreft.make_multiple_position_supervised_data_module(
        tokenizer=tokenizer,
        model=model,
        inputs=inputs_list,
        outputs=outputs_list,
        positions="f1+l1",
        num_interventions=1,
        share_weights=True,
    )
    train_loader = TorchDataLoader(
        data_module["train_dataset"],
        shuffle=True,
        batch_size=batch_size,
        collate_fn=data_module["data_collator"],
        generator=torch.Generator().manual_seed(seed),
    )

    optimizer = torch.optim.AdamW(
        ax_model.parameters(), lr=lr, weight_decay=0.0,
    )
    num_steps = epochs * max(1, len(train_loader))
    lr_scheduler = get_scheduler(
        "linear", optimizer=optimizer,
        num_warmup_steps=0, num_training_steps=num_steps,
    )

    # Training loop
    for epoch in range(epochs):
        epoch_loss = 0.0
        n_steps = 0
        for batch in train_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            unit_locations = {"sources->base": (
                None,
                batch["intervention_locations"].permute(1, 0, 2).tolist(),
            )}

            optimizer.zero_grad()

            _, cf_outputs = ax_model(
                base={
                    "input_ids": batch["input_ids"],
                    "attention_mask": batch["attention_mask"],
                },
                unit_locations=unit_locations,
                labels=batch["labels"],
                use_cache=False,
            )

            loss = cf_outputs.loss.mean()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(ax_model.parameters(), 1.0)
            optimizer.step()
            lr_scheduler.step()

            epoch_loss += loss.item()
            n_steps += 1

        print(f"  Epoch {epoch+1}/{epochs}  avg_loss={epoch_loss/max(1,n_steps):.4f}")

    print("[Step B] Done.")

    # Extract weights
    with torch.no_grad():
        key = list(ax_model.interventions.keys())[0]
        intervention = ax_model.interventions[key]
        
        R_gt_cols = intervention.rotate_layer.weight  # (d_model, rank)
        R_gt = R_gt_cols.T.float().cpu()              # (rank, d_model)

        W_gt = intervention.learned_source.weight.float().cpu()
        b_gt = (intervention.learned_source.bias.float().cpu()
                if intervention.learned_source.bias is not None else None)

    print(f"  Extracted: R_gt={tuple(R_gt.shape)}, W_gt={tuple(W_gt.shape)}")
    return {"R_gt": R_gt, "W_gt": W_gt, "b_gt": b_gt}


# ===========================================================================
# Step C — Load our weights
# ===========================================================================

def load_our_weights(vector_dir: Path, layer: int) -> dict:
    meta = torch.load(
        vector_dir / "metadata.pt",
        map_location="cpu",
        weights_only=False,
    )
    R_ours = meta["rotate_basis"][layer].float()    # (rank, d_model)
    W_ours = meta["learned_weight"][layer].float()  # (rank, d_model)
    b_map = meta.get("learned_bias") or {}
    b_ours = b_map.get(layer)
    if b_ours is not None:
        b_ours = b_ours.float()
    return {"R_ours": R_ours, "W_ours": W_ours, "b_ours": b_ours}


# ===========================================================================
# Step D — Compare and report
# ===========================================================================

def compare_and_report(ours: dict, gt: dict, layer: int) -> dict:
    R_ours, W_ours = ours["R_ours"], ours["W_ours"]
    R_gt,   W_gt   = gt["R_gt"],    gt["W_gt"]
    r, d = R_ours.shape

    sep = "=" * 62
    print(f"\n{sep}")
    print(f"  QUANTITATIVE COMPARISON — Layer {layer}  (rank={r}, d_model={d})")
    print(sep)

    # Sanity: orthonormality
    oe_ours = orthonormality_err(R_ours)
    oe_gt   = orthonormality_err(R_gt)
    print(f"\n[Sanity] ||R R^T - I||_F  (should ≈ 0)")
    print(f"  Ours : {oe_ours:.6f}")
    print(f"  GT   : {oe_gt:.6f}")

    # 1. Principal angles of R
    pa_R = principal_angles(R_ours, R_gt)
    cos_pa_R = pa_R.cos()
    print(f"\n[1] Principal angles (R subspace) [°]:")
    print(f"  " + "  ".join(f"{a*180/3.14159:.1f}°" for a in pa_R.tolist()))
    print(f"  cos(angles): " + "  ".join(f"{c:.4f}" for c in cos_pa_R.tolist()))
    print(f"  Mean cos = {cos_pa_R.mean().item():.4f}  (1.0 → identical subspaces)")

    # 2. Projector Frobenius distance
    frob_raw, frob_norm = projector_frobenius(R_ours, R_gt)
    print(f"\n[2] Projector distance ||P_ours - P_gt||_F:")
    print(f"  Raw        = {frob_raw:.4f}")
    print(f"  Normalised = {frob_norm:.4f}  (0 → identical, max≈1)")

    # 3. W subspace comparison
    if r == 1:
        cos_W = cos_sim_flat(W_ours, W_gt)
        print(f"\n[3] W cos-sim (r=1): {cos_W:.4f}  (1.0 → identical)")
        pa_W_mean = abs(cos_W)
    else:
        pa_W = subspace_principal_angles(W_ours, W_gt)
        cos_pa_W = pa_W.cos()
        cos_W_flat = cos_sim_flat(W_ours, W_gt)
        print(f"\n[3] W subspace principal angles [°]:")
        print(f"  " + "  ".join(f"{a*180/3.14159:.1f}°" for a in pa_W.tolist()))
        print(f"  Mean cos = {cos_pa_W.mean().item():.4f}")
        print(f"  Flat cos-sim(W_ours, W_gt) = {cos_W_flat:.4f}")
        pa_W_mean = cos_pa_W.mean().item()

    # 4. Bias comparison
    b_ours, b_gt = ours.get("b_ours"), gt.get("b_gt")
    cos_b = frob_b = None
    if b_ours is not None and b_gt is not None:
        cos_b  = cos_sim_flat(b_ours, b_gt)
        frob_b = (b_ours - b_gt).norm().item()
        print(f"\n[4] Bias: cos-sim={cos_b:.4f}  ||Δb||={frob_b:.4f}")

    # Summary
    print(f"\n{sep}")
    print(f"  SUMMARY")
    print(f"  R subspace mean cos(principal angle) : {cos_pa_R.mean().item():.4f}")
    print(f"  R projector distance (normalised)    : {frob_norm:.4f}")
    print(f"  W subspace mean cos(principal angle) : {pa_W_mean:.4f}")
    print(sep)

    return {
        "layer": layer,
        "R_orth_err_ours": oe_ours,
        "R_orth_err_gt":   oe_gt,
        "R_principal_angles_deg": [a*180/3.14159 for a in pa_R.tolist()],
        "R_mean_cos_principal_angle": cos_pa_R.mean().item(),
        "R_max_principal_angle_deg":  pa_R.max().item() * 180 / 3.14159,
        "R_projector_frob_raw":       frob_raw,
        "R_projector_frob_norm":      frob_norm,
        "W_mean_cos_principal_angle": pa_W_mean,
        "bias_cos_sim":  cos_b,
        "bias_frob":     frob_b,
    }


# ===========================================================================
# Main
# ===========================================================================

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--layer",      type=int,   default=10)
    parser.add_argument("--n-samples",  type=int,   default=100)
    parser.add_argument("--epochs",     type=int,   default=3)
    parser.add_argument("--lr",         type=float, default=5e-3)
    parser.add_argument("--rank",       type=int,   default=4)
    parser.add_argument("--batch-size", type=int,   default=4)
    parser.add_argument("--device",     default="cuda:0")
    parser.add_argument("--seed",       type=int,   default=42)
    parser.add_argument("--dataset",    default="refusal_cast_responses",
                        help="Dataset name in the registry")
    parser.add_argument("--skip-our-run", action="store_true",
                        help="Skip running our pipeline; load existing vector instead")
    parser.add_argument("--our-vector-dir",
                        default=str(REPO_ROOT / "Vector" / "LOREFT" / "concept500_compare"))
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    os.chdir(str(REPO_ROOT))

    # ---- Step A: Train our LoReFT via CLI ----
    vector_dir = Path(args.our_vector_dir)
    if not args.skip_our_run:
        vector_dir = run_our_pipeline(
            layer=args.layer, n_samples=args.n_samples,
            epochs=args.epochs, lr=args.lr, rank=args.rank,
            device=args.device, seed=args.seed, dataset=args.dataset,
        )
    else:
        print(f"[Step A] Skipping — using existing vector at: {vector_dir}")

    meta_path = vector_dir / "metadata.pt"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"Metadata not found: {meta_path}\n"
            "Run without --skip-our-run to extract first."
        )

    # ---- Step B: Train PyReFT GT ----
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.model_max_length = 4096

    data = _load_cast_refusal_data(n_samples=args.n_samples, tokenizer=tokenizer, dataset=args.dataset)
    print(f"  Loaded {len(data)} training samples.")

    gt_weights = train_pyreft_gt(
        data=data,
        tokenizer=tokenizer,
        layer=args.layer,
        rank=args.rank,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
        device=args.device,
        seed=args.seed,
    )

    # ---- Step C: Load our weights ----
    our_weights = load_our_weights(vector_dir, layer=args.layer)
    print(f"\n[Step C]")
    print(f"  Ours → R: {tuple(our_weights['R_ours'].shape)}, W: {tuple(our_weights['W_ours'].shape)}")
    print(f"  GT   → R: {tuple(gt_weights['R_gt'].shape)},   W: {tuple(gt_weights['W_gt'].shape)}")

    # ---- Step D: Compare ----
    metrics = compare_and_report(our_weights, gt_weights, layer=args.layer)

    # Save JSON report
    out_path = vector_dir / "comparison_metrics.json"
    with open(out_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"\nMetrics written to: {out_path}")


if __name__ == "__main__":
    main()
