model_task: "text_to_image_generation"
dataset: "coco-captions-concepts"
src_subsets: ["pink_elephant"]
dst_subsets: ["none"]
prompt_subset: ["pink_elephant"]
default_evaluation: ['text_to_image_generation', 'clip_score']