name: aura
pooling_op: max
estimation_strategy: atonce
state_path: null
hook_params:
  intervention_position: all
  strength: 1.0
  device: ${device}
  dtype: ${dtype:torch.float32}
  quantiles_src: q_all